# Site settings
baseurl = "https://gifaldyazkaa.vercel.app/"
languageCode = "en-us"
title = "Gifaldy Azka"
theme = "hugo-stellar-theme"

googleAnalytics = "277821425"

[params]
  [params.header]
    title = "Welcome!"
    description = 'Hello there! Welcome to my personal website!'


  [[params.navigation]]
    name = "Introduction"
    href = "#intro"

  [[params.navigation]]
    name = "Skills"
    href = "#skills"

  [[params.navigation]]
    name = "Projects"
    href = "#projects"

  [[params.navigation]]
    name = "Contact"
    href = "#contact"

  [params.intro]
    title = "Hello There!"
    description = "Hello there and Welcome! Let me introducing myself, My name is Gifaldy Azka. Front-end Website and Discord Bot Developer. Code and make things at Internet."
    image = "images/profilepicture.png"

  [[params.section]]
    id = "skills"
    title = "Skills"
    description = ""
    
    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "Code"
        description = "Code anything and now i can write code in over 6+ Languages. Writing a Discord Bots, or Code a Website. Yes i can!"
        icon = "fa-code"

      [[params.section.feature]]
        title = "Git"
        description = "When code something, I always using Git. Most used Version Control System to Manage Code."
        icon = "fa-code-fork"

      [[params.section.feature]]
        title = "Communication"
        description = "Very Important things to communicate with Other Developers, Client, or whoever."
        icon = "fa-comment-o"
    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [[params.section]]
    id = "projects"
    title = "Projects"
    description = ""

    [params.section.statistics]
      enable = true
      [[params.section.statistic]]
        icon = "fa-book"
        value = "4+"
        text = "Running Projects"
      [[params.section.statistic]]
        icon = "fa-check"
        value = "9+"
        text = "Projects Done"
      [[params.section.statistic]]
        icon = "fa-folder-open-o"
        value = "20+"
        text = "Total Projects"

    [params.section.content]
      enable = false
      text = "<a href='https://exxyll.github.io'><b>1#</b> Exxyll - A Multipurose Discord Bot</a>"

    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "See Project List"
        buttonUrl = "https://github.com/gifaldyazkaa?tab=repositories"


  [[params.section]]
    id = "contact"
    title = "Get in touch"
    description = "Feel free to contacting me! If you have a question, or just want to hanging out! I mostly active at Discord Platform! You can add me below or Join my servers to hang out with me!"
    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Discord Profile"
        buttonUrl = "https://discord.com/users/788260234409672754"
        customClass = "special"
      [[params.section.footer.action]]
        buttontext = "Join My Server"
        buttonUrl = "https://discord.gg/j2MfuWySfD"

  [params.footer]
    enable = true
    id = "contactme"
    title = "Built with"
    description = "This website is built with Hugo. The world's fastest framework for building websites. Most popular open-source static site generators (SSG). Written in Golang"

    second_title = "Contact Me"
    email = "gifaldyazka@yahoo.com"

    [[params.footer.action]]
      href = "https://gohugo.io"
      buttontext = "Learn More about Hugo"

    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "https://twitter.com/falcxxr"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://facebook.com/falcxx"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "https://instagram.com/falcxxr"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "mailto:gifaldyazka@yahoo.com"

    [params.footer.copyright]
      enable = true
      text = "© Gifaldy Azka 2021"
